### ISSUE TITLE
Song Buttons Ugly on Mobile

### ISSUE THREAD

**Issue by ckester99** [ckester99/crowd-surf#10]
## Issue
The y margin on the buttons is too large on mobile, the width is already responsive

## Recommended Resolution
Developer needs to determine the best way to determine the cleanest way to change the y margin on mobile.
The two ways that come to mind are:
- media query in css to determine breakpoint and change .song-button class y margin
- apply classes to each button in html to use tailwind's media breakpoints and padding on each button

## Desktop Client Display
![image](https://user-images.githubusercontent.com/43022124/202855389-239ab5e3-bcfa-492e-86e7-1b3a055acc64.png)

## Mobile Client Display
![image](https://user-images.githubusercontent.com/43022124/202855437-8c62fe3f-9a26-46a0-bcc9-3786a6a54b85.png)

**Comment by abitsalihu** [comment]
Hey @ckester99, I would like to help with this issue. :)

**Comment by RussC22** [comment]
I'm finishing up on it; I got the buttons to match the mock up. I am working on the test content sections now. I will be pushing a update in a bit.

**Comment by ckester99** [comment]
Spacing looks good on mobile devices now
